name: Ruby with Cucumber

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.5 # Use a versão de Ruby desejada
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Bundler
        run: gem install bundler
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec cucumber -p default -p headless

