name: Ruby

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1 # Use a versão mais recente
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: log untrusted output
      run: |
        # disable command workflow processing
        echo "::stop-commands::`echo -n ${{ github.token }} | sha256sum | head -c 64`"
        # log untrusted output
        echo "::add-path::$(ruby -e 'puts Gem.user_dir')/bin"
        echo "::add-path::$(ruby -e 'puts Gem.user_dir')/bin"
        # enable workflow command processing
        echo "::`echo -n ${{ github.token }} | sha256sum | head -c 64`::"
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    - name: Run tests
      run: cucumber -p default -p headless -t@empty_data_login
    - name: Generate Test Reports
      run: |
        # Comandos para gerar relatórios de teste, se aplicável
    - name: Notify Test Results
      run: |
        # Comandos para notificar a equipe sobre os resultados dos testes, se aplicável


